### ISSUE TITLE
Implementation of iterators

### ISSUE THREAD

**Issue by ffranchina** [bebosudo/advanced-programming#2]
Hello @asartori86!
Me and @bebosudo were thinking about a good implementation of iterators for the binary search tree class. We thought about many different possibilities, each with its pros and cons.

In particular we ended up dividing the implementations into two main categories:
- the ones that "duplicate" the structure so that, even if the tree is modified after the instantiation, the output of the iterator stays the same
- the ones that work "online" and, if the structure is altered, they adapt accordingly and give data always consistent with the modified structure

For example, consider the following code:
```
// insertion of number from 1 to 20 into the tree...

for (IteratorClass it = tree.begin(); it->key() < 10; it++) { cout<<it; }

tree.erase(15);

for (; it != tree.end(); it++) { cout<<it;  }
```

in the first case would print all the numbers from 1 to 20, since the tree nodes have been copied elsewhere at the iterator initialization;
in the second case it would print numbers from 1 to 20, 15 excluded, when using the second method.

Both of the approaches presents a trade-off of the kind flexibility vs memory-frugality.
Would it be possible to have your opinion about that?
Thank you in advance for your time!

**Comment by asartori86** [comment]
@ffranchina @bebosudo,
the iterators are used to navigate the **current** tree, so it must be consistent with the tree. If you delete the node with key 15, I expect to not see that node using iterators. Iterators are **generalized pointers** so they must be lightweight like pointers (they do not need to use additional memory).

I gave a quick look at your code (master branch), in particular, the use of a template comparison. While it may work for function objects that have a default constructor, it doesn't work at all for function objects that do not have a default constructor. Moreover, it cannot work when I want to use a simple function as a comparison.
What I suggest is something of the following type
```
template <typename K, typename V, typename cmp>
class Tree {
  cmp comparator;
public:
  Tree(com op = cmp{}) : comparator{op} {}
};
```
In this way I can easily use either a function object or a function
```
template <typename K>
struct FO{
bool operator()(const K& k1, const K& k2){
  return k1<k2; // of course, if I need to write such a class I have to perform more complex actions
}
};

template <typename K>
bool func(const K& k1, const K& k2){
  return k1>k2;
}
```
In the main
```
Tree<int,int,FO> t_fo;
Tree<int,int, decltype(&func)> t_func{func};
```
if the class `FO` had a non default constructor I would construct `t_fo` as follows
```
Tree<int,int,FO> t_fo{ FO{all, the, needed, parameters} };
```
Moreover, pay attention on how you use `comparator`
```
if (k1 < k2) ---> if (comparator(k1, k2))
```
`if (k1 > k2)` is not `if (!comparator(k1,k2))`

because `!comparator(k1,k2)` returns true when the keys are equal. So 
```
if (k1 > k2) ---> if(comparator(k2,k1))
```
and
```
if (k1==k2) ---> if ( (!comparator(k1,k2)) && (!comparator(k2,k1)))
```

As a final remark, please mark **const** what should be constant (e.g., the keys when you compare them, when you call insert, when you call find...)

**Comment by bebosudo** [comment]
Thanks for the reply @asartori86!
regarding the iterator, we came up with a couple of ideas:

1. use a naive implementation, by `find`ing every time the successor of the current node key: this means that iterating over the tree would require `logN` (for every `find` operation in the case of a balanced tree) * `N` operations.
1. add a raw pointer to the parent inside each node: there's some more memory consumption (~ sizeof(pointer) more for each node);
1. implement a _threaded_ BST, as shown in Donald E. Knuth-The Art of Computer Programming, Vol. 1 - Fundamental Algorithms, 3rd Edition-Addison-Wesley Professional (1997), chapter 2, section 3.1, pag. 324, from which I take the following picture:

![Image of a Threaded BST](https://i.imgur.com/P3ZMjoR.png)

This has the advantage that we could use the otherwise wasted left and right pointers in the leaves (but we should use shared pointers, which introduce a little more overhead than unique pointers), but it makes iteration really easy.

What could be the best implementation, in your opinion?


Many thanks also for the review on the comparator and the tip on the `const`.

**Comment by asartori86** [comment]
@bebosudo @ffranchina,
I vote for the easiest (in term of number of lines of code required in each function) solution that is the number 2: inside the node there is a raw pointer that points to another node. This information should/could be used in the implementation of the `operator++` method for the iterator.
think carefully which node should point to in order to minimize the number of lines of code you have to write in all the involved functions. If you will, we can discuss a bit personally. I am in office 107 this afternoon and tomorrow afternoon. Let me know

**Comment by bebosudo** [comment]
Thanks for the pointer! no pun intended.

Unfortunately, we are not in sissa today. Thanks anyway for the proposal.

See you soon!

**Comment by asartori86** [comment]
@ffranchina @bebosudo 

actually, the office 107 is at miramare old sissa building
